#!/bin/sh
set -e

# Source debconf library.
. /usr/share/debconf/confmodule

pip3 install -r /usr/share/openalpr-agent-failsafe/requirements.txt
update-rc.d openalpr-agent-failsafe defaults 95 > /dev/null

invoke-rc.d openalpr-agent-failsafe restart



db_stop
